# Generated by Django 5.0.1 on 2024-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
